services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - net

  backend:
    platform: linux/x86_64
    container_name: backend
    build:
      context: ./
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres:5432/postgres"
    depends_on:
      - postgres
    networks:
      - net
networks:
  net:
    name: net
